
```{r}
rm(list=ls())
library(fpp3)
library(patchwork) # to easily place graphs next to each other
```

```{r}
# why r = alpha-1? it's our assumption
# stemplots, to show how the sum of infinite sequence with r less than 1sums to 1 and how fast
# 26:10 video don't understand explanation in the bracket, why waited average, casue equal to 1
# why the new forecast are taken into account? if yes, it should infuence the forecasts
# so the weights will always decrease with more distant forecast, but alpha tells how fast the weights decrease?
# the higer the alpha the faster the weight decreases
# by design the forecast are constant, flat, it's equak to the first forecast we make outside the training data
# we will guess alpha basing on traing area to get fitted values, find alpha that minimises SSE - sum of square residuals, and then we'll use the same alpha for forecasts
# no explicit formula, using iterations
```

```{r}
algeria_economy <- global_economy %>%
  filter(Country == "Algeria")

algeria_economy %>%
  autoplot(Exports) +
  labs(y = "% of GDP", title = "Exports: Algeria")
```


```{r}
# Estimate parameters
fit <- algeria_economy %>%
  model(ETS(Exports ~ error("A") + trend("N") + season("N")))
fit
```

```{r}
fitted_vals <- 
  fit %>% augment() %>% select(Year, Exports, .fitted)

fitted_vals
```

```{r}
# Print out the model parameters
ses_params <- tidy(fit)
ses_params
```

```{r}
# Store alpha
alpha <- ses_params$estimate[1]

weights <- vector("double") 
for (i in seq(1:nrow(fitted_vals))){
  # Compute the weight associated to each observation
  weights[[i]] <- alpha*((1-alpha)**(i-1))
}

# Add this column to the fitted values
fitted_vals$weight = rev(weights)

# Reverse the order of the dataframe to depict it more clearly
fitted_vals <- 
  fitted_vals %>% 
  arrange(desc(Year))
fitted_vals
```

```{r}
# Generate 5 step forecasts
fc <- fit %>%
  forecast(h = 5)
```


```{r}
fc %>%
  autoplot(algeria_economy) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit)) +
  labs(y="% of GDP", title="Exports: Algeria") +
  guides(colour = "none")
```

